name = "TransComp"
uuid = "b596f64e-e7eb-4ba8-8bcd-d8f82e2b38d9"
license = "MIT"
authors = ["Antonia Golab <antonia.golab@tuwien.ac.at>"]
description = "Regional transport sector model"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Gurobi = "1.0"
JuMP = "1.9"
ProgressMeter = "1.11.0"
YAML = "0.4"
julia = "1.6"
