[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TransComp = "3fb1ea32-fe1d-487b-b926-6db75a8950b6"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Dates = "1"
JuMP = "1.9"
Printf = "1.10"
TransComp = "0.1"
YAML = "0.4"
julia = "1.6"
